#ifndef _CONFIG_SPEEDCONTROL_H_
#define _CONFIG_SPEEDCONTROL_H_


#if defined(HW_CHALLENGER_PLAST)

#define CONFIG_SPEEDCONTROL_USE 1
#define CONFIG_SPEED_TYPE_ROTARY
#define CONFIG_SPEED_ROTARY_CLOCK 10
#define CONFIG_SPEED_ROTARY_DATA 11
#define CONFIG_SPEED_ROTARY_BUTTON_DIGITAL 7 
#define CONFIG_CMD_MODE_LED A0
// #define CONFIG_SPEED_ROTARY_BUTTON_ANALOG 0
// #define CONFIG_SPEED_ROTARY_BUTTON_THRESHOLD 0
// #define CONFIG_SPEED_POT_INPUT 0

#elif defined(HW_CHALLENGER2)

#define CONFIG_SPEEDCONTROL_USE 1
#define CONFIG_SPEED_TYPE_ROTARY
#define CONFIG_SPEED_ROTARY_CLOCK 11
#define CONFIG_SPEED_ROTARY_DATA 12
#define CONFIG_SPEED_ROTARY_BUTTON_DIGITAL A0
#define CONFIG_CMD_MODE_LED 4

// #define CONFIG_SPEED_ROTARY_BUTTON_ANALOG 0
// #define CONFIG_SPEED_ROTARY_BUTTON_THRESHOLD 0

/** ----- Potentiometer configuration parameters ----- **/
// choose analog pin; if CONFIG_SPEED_TYPE == "ROTARY", this symbol is ignored

#define CONFIG_SPEED_POT_INPUT 0

#else 
// Make your own 
#endif

#endif 
